version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd frontend && npm cache clean --force
      - rm -rf node_modules package-lock.json
      - npm -v
      - npm install -g npm
      - npm i
  build:
    commands:
      - npm run build  # Builds the project
artifacts:
  files:
    - '**/*'
  base-directory: frontend/build  # Directory with output files (e.g., React app)
